spring:
  datasource:
    url: jdbc:h2:mem:votacaodb;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2
