spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/desafiovotacaodb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect